mm: mmzone: fix compile failure caused by adding new members in mem_section
When enabling PAGE_EXTENSION, we ran into the below 2 compile errors:

In file included from ./include/linux/gfp.h:5:0,
                 from ./include/linux/slab.h:14,
                 from ./include/linux/crypto.h:24,
                 from arch/x86/kernel/asm-offsets.c:8:
./include/linux/mmzone.h:1127:16: error: duplicate member ‘pad’
  unsigned long pad;
                ^~~
mm/sparse.c: In function ‘sparse_init’:
./include/linux/compiler.h:522:38: error: call to
‘__compiletime_assert_535’ declared with attribute error: BUILD_BUG_ON
failed: !is_power_of_2(sizeof(struct mem_section))
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)

Remove both pad members and make the structure 16 bytes aligned, then it
also satisfies the power-of-2 alignment.

Signed-off-by: Yang Shi <yang.shi@linux.alibaba.com>
Reviewed-by: George Zhang <georgezhang@linux.alibaba.com>
Reviewed-by: Wenwei Tao <wenwei.tao@linux.alibaba.com>